### ISSUE TITLE
replaces road textures

### ISSUE THREAD

**Issue by inikishev** [mattkimber/timberwolfs_road_vehicles#2]
hi this seems to replace road textures
![image](https://github.com/mattkimber/timberwolfs_road_vehicles/assets/76593873/f0d37a5b-1c61-4ac2-aff7-6948039cbc5a)

**Comment by mattkimber** [comment]
This is coming from another set, there are no road textures in Road Vehicles at all. It's possible something else you have active defines some kind of secret roadtype with a label I use, but unfortunately I can't support compatibility issues with anything other than an otherwise unmodified game or Timberwolf's Roads; it takes too long to investigate each occurrence (especially because so many don't have source code available) and I've had too many situations where I put in all the work only for the roadset author to immediately re-break it on their next update by using a road label in a weird way again.
